### PR TITLE
Able to crop images into any rectangular size and fill their background

### PR DESCRIPTION
**Pull request by zayass**
Refactored version of https://github.com/zayass/image-maven-plugin/pull/1

### CODE REVIEW

**Comment by zayass** [comment]
Published to Sonatype OSSRH: https://oss.sonatype.org/content/groups/public wait for sync

**Comment by zayass** [comment]
Synced

**Comment by jtulach** [comment]
I am afraid the version 1.2 of your plugin is completely broken. Here is a project (http://xelfi.cz/demopage.zip) that used to work with version 1.1, but when switching to 1.2, the "mvm clean install" fails. And I have not tried to crop the image yet! Below is the diff I used to switch to version 1.2:

```
diff -r 8e659cfee056 client-ios/pom.xml
--- a/client-ios/pom.xml    Mon Feb 02 19:47:33 2015 +0100
+++ b/client-ios/pom.xml    Mon Feb 02 20:14:14 2015 +0100
@@ -73,7 +73,7 @@
             <plugin>
                 <groupId>com.filmon.maven</groupId>
                 <artifactId>image-maven-plugin</artifactId>
-                <version>1.1</version>
+                <version>1.2</version>
                 <executions>
                     <execution>
                         <goals>
```

**Comment by zayass** [comment]
try 1.3-SNAPSHOT from https://oss.sonatype.org/content/repositories/snapshots/

**Comment by jtulach** [comment]
1.3-SNAPSHOT seems to work OK for my purposes.

**Comment by zayass** [comment]
It was problem with chaining apears only when you generate multiple images from one source

**Comment by jtulach** [comment]
Once 1.3 version is available at maven central, I will change my project to use it.

**Comment by jtulach** [comment]
Don't you want to release the fixed version on Maven central? I am not going to use a snapshot dependency from my archetype...

**Comment by zayass** [comment]
fix released as 1.2.1

**Pull request merged**
